// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzs0zB1PSt_srloEajISXRc5uvxqcUA10',
    appId: '1:72996944730:web:a4b0803b765a328f499163',
    messagingSenderId: '72996944730',
    projectId: 'rideshare-b3eea',
    authDomain: 'rideshare-b3eea.firebaseapp.com',
    storageBucket: 'rideshare-b3eea.appspot.com',
    measurementId: 'G-NZ2VR64G1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzs0zB1PSt_srloEajISXRc5uvxqcUA10',
    appId: '1:72996944730:android:8adc4dcdf9735500499163',
    messagingSenderId: '72996944730',
    projectId: 'rideshare-b3eea',
    storageBucket: 'rideshare-b3eea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzs0zB1PSt_srloEajISXRc5uvxqcUA10',
    appId: '1:72996944730:ios:e5ab0d880ed7d4dc499163',
    messagingSenderId: '72996944730',
    projectId: 'rideshare-b3eea',
    storageBucket: 'rideshare-b3eea.appspot.com',
    iosBundleId: 'com.example.RideShare',
  );
}
