name: corider
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_auth: ^5.5.1
  flutter_login: ^5.0.0
  firebase_storage: ^12.4.4
  image: ^4.0.17
  google_maps_flutter: ^2.3.0
  zego_uikit_prebuilt_call: ^4.16.24
  location:  # temporary fix for android compile error
    git:
      url: https://github.com/781flyingdutchman/flutterlocation.git
      ref: V4
      path: packages/location
  provider: ^6.0.5
  cloud_firestore: ^5.6.5
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  geocoding: ^3.0.0
  shared_preferences: ^2.1.2
  uuid: ^4.5.1
  tuple: ^2.0.2
  intl: ^0.20.2
  cached_network_image: ^3.2.3
  flutter_chat_ui: ^1.6.8
  flutter_chat_types: ^3.6.1
  file_picker: ^8.3.7
  open_filex: ^4.3.2
  http: ^1.3.0
  overlay_support: ^2.1.0
  flutter_local_notifications: ^19.0.0
  geolocator: ^13.0.3
  libphonenumber_plugin: ^0.3.3
  flutter_dotenv: ^5.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"


flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/images/logo.png
    - assets/icon/icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
